# .github/workflows/ci.yml

# Workflow name
name: CI - Build and Push Docker Image

# Triggers: runs every time there is a push to the “main” branch
on:
  push:
    branches: [ "main" ]
  # Allows you to manually start this workflow from the Actions tab in GitHub.
  workflow_dispatch:

jobs:
  build-and-push:
    # The virtual machine on which the job will run
    runs-on: ubuntu-latest

    steps:
      # Step 1: Retrieve the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2: Set up QEMU 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Étape 3: set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Étape 4: Connect to docker hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Étape 5: Construct the image and push on github
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: rickyr7/car-price-api:latest
	# End
